package org.moana.bean;

import java.util.Date;


public class UserOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.user_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.ticket_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private String ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.purchase_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private Date purchaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.purchase_num
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private Integer purchaseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.remark
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.sum_price
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private Long sumPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uses_order.display_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    private Date displayTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.id
     *
     * @return the value of uses_order.id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.id
     *
     * @param id the value for uses_order.id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.user_id
     *
     * @return the value of uses_order.user_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.user_id
     *
     * @param userId the value for uses_order.user_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.ticket_id
     *
     * @return the value of uses_order.ticket_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.ticket_id
     *
     * @param ticketId the value for uses_order.ticket_id
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId == null ? null : ticketId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.purchase_time
     *
     * @return the value of uses_order.purchase_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.purchase_time
     *
     * @param purchaseTime the value for uses_order.purchase_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.purchase_num
     *
     * @return the value of uses_order.purchase_num
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public Integer getPurchaseNum() {
        return purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.purchase_num
     *
     * @param purchaseNum the value for uses_order.purchase_num
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setPurchaseNum(Integer purchaseNum) {
        this.purchaseNum = purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.remark
     *
     * @return the value of uses_order.remark
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.remark
     *
     * @param remark the value for uses_order.remark
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.sum_price
     *
     * @return the value of uses_order.sum_price
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public Long getSumPrice() {
        return sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.sum_price
     *
     * @param sumPrice the value for uses_order.sum_price
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setSumPrice(Long sumPrice) {
        this.sumPrice = sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uses_order.display_time
     *
     * @return the value of uses_order.display_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public Date getDisplayTime() {
        return displayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uses_order.display_time
     *
     * @param displayTime the value for uses_order.display_time
     *
     * @mbggenerated Sun Jan 08 14:33:09 CST 2017
     */
    public void setDisplayTime(Date displayTime) {
        this.displayTime = displayTime;
    }
}